### PR TITLE
feat: add phoenix route to plug metadata

### PR DESCRIPTION
**Pull request by btkostner**
This adds the phoenix route to plug metadata, so you will be able to get `/resource/:id` as well as the regular url like `/resources/1234`. It depends on `Phoenix.Router` code, so I can't add tests, but I did test locally.

### CODE REVIEW

**Comment by btkostner** [comment]
Worth noting that this will require Phoenix 1.5.0 or greater

**Comment by AndrewDryga** [comment]
Hello @btkostner, I believe we already are writing `conn.request_path` both in GKE and DataDog formatter, can you please share a use case when it's not enough?

**Comment by btkostner** [comment]
This will have the params in the url. `/products/1234` is what we currently have and `/products/:id` is what this adds. At least for Datadog, the APM includes it and it's much easier to query by.

**Comment by AndrewDryga** [comment]
@btkostner can we keep this change to DataDog only? For Google Cloud, we already have a full request path. Other than that thank you and LGTM.

**Comment by btkostner** [comment]
Sounds good. PR updated!

**Review by AndrewDryga — APPROVED** [review]

**Pull request merged**
