### PR TITLE
README: Fix broken SourceLevel image and link

### PR DESCRIPTION
**Pull request by sgerrand**
💁 It looks like SourceLevel changed their URL structure at some point between when this badge was added to `README.md` and now. These changes fix those URLs and enable the badge image to render again.

### CODE REVIEW

**Review by AndrewDryga — APPROVED** [review]

**Comment by AndrewDryga** [comment]
@sgerrand can you please fix the conflict and I'll merge it :). Thank you ❤️

**Comment by sgerrand** [comment]
Shall do!

**Comment by sgerrand** [comment]
👋 @AndrewDryga: All done, awaiting your review.

**Comment by AndrewDryga** [comment]
Thank you :)

**Pull request merged**
