### PR TITLE
Allow pids to be logged in the metadata

### PR DESCRIPTION
**Pull request by anthonyfalzetti**

### CODE REVIEW

**Comment by AndrewDryga** [comment]
Hello, @anthonyfalzetti! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/Nebo15/logger_json/pulls/21). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by AndrewDryga** [comment]
Hello @anthonyfalzetti, can you provide a little bit details about your use case? I fell like you can get what you want without code changes

**Comment by anthonyfalzetti** [comment]
Hello @AndrewDryga, 

What I would like to be able to do is track processes. I will be sending these logs to splunk and I would like to be able to be able to group a complete process by an identifier. Up till now that has been the pid. I have created a sample app that can demonstrate the proposed changes.

```json
{"log":"Starting the Application","pid":"#PID<0.248.0>","severity":"INFO","time":"2019-04-05T08:43:43.222Z"}
{"log":"Kicking off the Server","pid":"#PID<0.250.0>","severity":"INFO","time":"2019-04-05T08:43:43.222Z"}
```

versus as the code currently stands: 

```log
iex(1)> :gen_event handler LoggerJSON installed in Logger terminating
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for #PID<0.248.0>, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for: Any, Atom, BitString, Date, DateTime, Decimal, Float, Integer, Jason.Fragment, List, Map, NaiveDateTime, Time
        (jason) lib/jason.ex:199: Jason.encode_to_iodata!/2
        (logger_json) lib/logger_json.ex:299: LoggerJSON.format_event/5
        (logger_json) lib/logger_json.ex:234: LoggerJSON.log_event/5
        (logger_json) lib/logger_json.ex:139: LoggerJSON.handle_event/2
        (stdlib) gen_event.erl:577: :gen_event.server_update/4
        (stdlib) gen_event.erl:559: :gen_event.server_notify/4
        (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

I would be interested in alternative ways to find this information and perhaps I missed something in the configuration. 

link to sample repo: https://github.com/anthonyfalzetti/test_logging

**Comment by AndrewDryga** [comment]
@anthonyfalzetti unfortunately, your fix would only work if pid is explicitly listed in `metadata`, but if `metadata` is set to `:all` it would fail and go through all options there would be an overkill. Also, later we would need to add `inspect` call for functions, references, and ports which is not the goal for the logger.

Instead, you can implement `Jason.Encoder` protocol for PIDs and any other datatypes you want to be logged in JSON and not supported by Jason natively.

Other option would be to define a custom formatter that adds `:pid` just for you.

**Comment by anthonyfalzetti** [comment]
Thanks @AndrewDryga I will work on another solution.

**Pull request closed without merging**
